// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: clip.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EncodingService_EncodeText_FullMethodName   = "/EncodingService/EncodeText"
	EncodingService_EncodeImage_FullMethodName  = "/EncodingService/EncodeImage"
	EncodingService_GetImageSpec_FullMethodName = "/EncodingService/GetImageSpec"
)

// EncodingServiceClient is the client API for EncodingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Worker service definition.
type EncodingServiceClient interface {
	// EncodeText perform text embedding
	EncodeText(ctx context.Context, in *EncodeTextRequest, opts ...grpc.CallOption) (*EncodeResponse, error)
	// Notify worker to queue unprocessed asset to processing queue.
	EncodeImage(ctx context.Context, in *EncodeImageRequest, opts ...grpc.CallOption) (*EncodeResponse, error)
	// Return the image spec to be encoded.
	GetImageSpec(ctx context.Context, in *GetImageSpecRequest, opts ...grpc.CallOption) (*GetImageSpecResponse, error)
}

type encodingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEncodingServiceClient(cc grpc.ClientConnInterface) EncodingServiceClient {
	return &encodingServiceClient{cc}
}

func (c *encodingServiceClient) EncodeText(ctx context.Context, in *EncodeTextRequest, opts ...grpc.CallOption) (*EncodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncodeResponse)
	err := c.cc.Invoke(ctx, EncodingService_EncodeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encodingServiceClient) EncodeImage(ctx context.Context, in *EncodeImageRequest, opts ...grpc.CallOption) (*EncodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncodeResponse)
	err := c.cc.Invoke(ctx, EncodingService_EncodeImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encodingServiceClient) GetImageSpec(ctx context.Context, in *GetImageSpecRequest, opts ...grpc.CallOption) (*GetImageSpecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImageSpecResponse)
	err := c.cc.Invoke(ctx, EncodingService_GetImageSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncodingServiceServer is the server API for EncodingService service.
// All implementations must embed UnimplementedEncodingServiceServer
// for forward compatibility.
//
// Worker service definition.
type EncodingServiceServer interface {
	// EncodeText perform text embedding
	EncodeText(context.Context, *EncodeTextRequest) (*EncodeResponse, error)
	// Notify worker to queue unprocessed asset to processing queue.
	EncodeImage(context.Context, *EncodeImageRequest) (*EncodeResponse, error)
	// Return the image spec to be encoded.
	GetImageSpec(context.Context, *GetImageSpecRequest) (*GetImageSpecResponse, error)
	mustEmbedUnimplementedEncodingServiceServer()
}

// UnimplementedEncodingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEncodingServiceServer struct{}

func (UnimplementedEncodingServiceServer) EncodeText(context.Context, *EncodeTextRequest) (*EncodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncodeText not implemented")
}
func (UnimplementedEncodingServiceServer) EncodeImage(context.Context, *EncodeImageRequest) (*EncodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncodeImage not implemented")
}
func (UnimplementedEncodingServiceServer) GetImageSpec(context.Context, *GetImageSpecRequest) (*GetImageSpecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImageSpec not implemented")
}
func (UnimplementedEncodingServiceServer) mustEmbedUnimplementedEncodingServiceServer() {}
func (UnimplementedEncodingServiceServer) testEmbeddedByValue()                         {}

// UnsafeEncodingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncodingServiceServer will
// result in compilation errors.
type UnsafeEncodingServiceServer interface {
	mustEmbedUnimplementedEncodingServiceServer()
}

func RegisterEncodingServiceServer(s grpc.ServiceRegistrar, srv EncodingServiceServer) {
	// If the following call panics, it indicates UnimplementedEncodingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EncodingService_ServiceDesc, srv)
}

func _EncodingService_EncodeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncodingServiceServer).EncodeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncodingService_EncodeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncodingServiceServer).EncodeText(ctx, req.(*EncodeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncodingService_EncodeImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncodingServiceServer).EncodeImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncodingService_EncodeImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncodingServiceServer).EncodeImage(ctx, req.(*EncodeImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncodingService_GetImageSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncodingServiceServer).GetImageSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncodingService_GetImageSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncodingServiceServer).GetImageSpec(ctx, req.(*GetImageSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EncodingService_ServiceDesc is the grpc.ServiceDesc for EncodingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EncodingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EncodingService",
	HandlerType: (*EncodingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncodeText",
			Handler:    _EncodingService_EncodeText_Handler,
		},
		{
			MethodName: "EncodeImage",
			Handler:    _EncodingService_EncodeImage_Handler,
		},
		{
			MethodName: "GetImageSpec",
			Handler:    _EncodingService_GetImageSpec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clip.proto",
}
