// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: clip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// input of text encoding
type EncodeTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeTextRequest) Reset() {
	*x = EncodeTextRequest{}
	mi := &file_clip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeTextRequest) ProtoMessage() {}

func (x *EncodeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeTextRequest.ProtoReflect.Descriptor instead.
func (*EncodeTextRequest) Descriptor() ([]byte, []int) {
	return file_clip_proto_rawDescGZIP(), []int{0}
}

func (x *EncodeTextRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

// input of image encoding
type EncodeImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeImageRequest) Reset() {
	*x = EncodeImageRequest{}
	mi := &file_clip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeImageRequest) ProtoMessage() {}

func (x *EncodeImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeImageRequest.ProtoReflect.Descriptor instead.
func (*EncodeImageRequest) Descriptor() ([]byte, []int) {
	return file_clip_proto_rawDescGZIP(), []int{1}
}

func (x *EncodeImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

// output of encoding.
type EncodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []byte                 `protobuf:"bytes,1,opt,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeResponse) Reset() {
	*x = EncodeResponse{}
	mi := &file_clip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeResponse) ProtoMessage() {}

func (x *EncodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeResponse.ProtoReflect.Descriptor instead.
func (*EncodeResponse) Descriptor() ([]byte, []int) {
	return file_clip_proto_rawDescGZIP(), []int{2}
}

func (x *EncodeResponse) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

// get image spec input
type GetImageSpecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageSpecRequest) Reset() {
	*x = GetImageSpecRequest{}
	mi := &file_clip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageSpecRequest) ProtoMessage() {}

func (x *GetImageSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageSpecRequest.ProtoReflect.Descriptor instead.
func (*GetImageSpecRequest) Descriptor() ([]byte, []int) {
	return file_clip_proto_rawDescGZIP(), []int{3}
}

// get image spec output
type GetImageSpecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageSpecResponse) Reset() {
	*x = GetImageSpecResponse{}
	mi := &file_clip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageSpecResponse) ProtoMessage() {}

func (x *GetImageSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageSpecResponse.ProtoReflect.Descriptor instead.
func (*GetImageSpecResponse) Descriptor() ([]byte, []int) {
	return file_clip_proto_rawDescGZIP(), []int{4}
}

func (x *GetImageSpecResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetImageSpecResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_clip_proto protoreflect.FileDescriptor

const file_clip_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"clip.proto\")\n" +
	"\x11EncodeTextRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"*\n" +
	"\x12EncodeImageRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\".\n" +
	"\x0eEncodeResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x01(\fR\tembedding\"\x15\n" +
	"\x13GetImageSpecRequest\"D\n" +
	"\x14GetImageSpecResponse\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height2\xb6\x01\n" +
	"\x0fEncodingService\x121\n" +
	"\n" +
	"EncodeText\x12\x12.EncodeTextRequest\x1a\x0f.EncodeResponse\x123\n" +
	"\vEncodeImage\x12\x13.EncodeImageRequest\x1a\x0f.EncodeResponse\x12;\n" +
	"\fGetImageSpec\x12\x14.GetImageSpecRequest\x1a\x15.GetImageSpecResponseB\rZ\v/service/pbb\x06proto3"

var (
	file_clip_proto_rawDescOnce sync.Once
	file_clip_proto_rawDescData []byte
)

func file_clip_proto_rawDescGZIP() []byte {
	file_clip_proto_rawDescOnce.Do(func() {
		file_clip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clip_proto_rawDesc), len(file_clip_proto_rawDesc)))
	})
	return file_clip_proto_rawDescData
}

var file_clip_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_clip_proto_goTypes = []any{
	(*EncodeTextRequest)(nil),    // 0: EncodeTextRequest
	(*EncodeImageRequest)(nil),   // 1: EncodeImageRequest
	(*EncodeResponse)(nil),       // 2: EncodeResponse
	(*GetImageSpecRequest)(nil),  // 3: GetImageSpecRequest
	(*GetImageSpecResponse)(nil), // 4: GetImageSpecResponse
}
var file_clip_proto_depIdxs = []int32{
	0, // 0: EncodingService.EncodeText:input_type -> EncodeTextRequest
	1, // 1: EncodingService.EncodeImage:input_type -> EncodeImageRequest
	3, // 2: EncodingService.GetImageSpec:input_type -> GetImageSpecRequest
	2, // 3: EncodingService.EncodeText:output_type -> EncodeResponse
	2, // 4: EncodingService.EncodeImage:output_type -> EncodeResponse
	4, // 5: EncodingService.GetImageSpec:output_type -> GetImageSpecResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clip_proto_init() }
func file_clip_proto_init() {
	if File_clip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clip_proto_rawDesc), len(file_clip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clip_proto_goTypes,
		DependencyIndexes: file_clip_proto_depIdxs,
		MessageInfos:      file_clip_proto_msgTypes,
	}.Build()
	File_clip_proto = out.File
	file_clip_proto_goTypes = nil
	file_clip_proto_depIdxs = nil
}
