// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of the asset.
type AssetStatus int32

const (
	AssetStatus_PENDING    AssetStatus = 0
	AssetStatus_PROCESSING AssetStatus = 1
	AssetStatus_PROCESSED  AssetStatus = 2
)

// Enum value maps for AssetStatus.
var (
	AssetStatus_name = map[int32]string{
		0: "PENDING",
		1: "PROCESSING",
		2: "PROCESSED",
	}
	AssetStatus_value = map[string]int32{
		"PENDING":    0,
		"PROCESSING": 1,
		"PROCESSED":  2,
	}
)

func (x AssetStatus) Enum() *AssetStatus {
	p := new(AssetStatus)
	*p = x
	return p
}

func (x AssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[0].Descriptor()
}

func (AssetStatus) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[0]
}

func (x AssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetStatus.Descriptor instead.
func (AssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

// NotifyProcessAssetRequest
type NotifyProcessAssetResquest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyProcessAssetResquest) Reset() {
	*x = NotifyProcessAssetResquest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyProcessAssetResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyProcessAssetResquest) ProtoMessage() {}

func (x *NotifyProcessAssetResquest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyProcessAssetResquest.ProtoReflect.Descriptor instead.
func (*NotifyProcessAssetResquest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyProcessAssetResquest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// NotifyProcessAssetResponse
type NotifyProcessAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        AssetStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=AssetStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyProcessAssetResponse) Reset() {
	*x = NotifyProcessAssetResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyProcessAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyProcessAssetResponse) ProtoMessage() {}

func (x *NotifyProcessAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyProcessAssetResponse.ProtoReflect.Descriptor instead.
func (*NotifyProcessAssetResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyProcessAssetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotifyProcessAssetResponse) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_PENDING
}

// NotifyScanCacheRequest
type NotifyScanCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyScanCacheRequest) Reset() {
	*x = NotifyScanCacheRequest{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyScanCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyScanCacheRequest) ProtoMessage() {}

func (x *NotifyScanCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyScanCacheRequest.ProtoReflect.Descriptor instead.
func (*NotifyScanCacheRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

// NotifyScanCacheResponse
type NotifyScanCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyScanCacheResponse) Reset() {
	*x = NotifyScanCacheResponse{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyScanCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyScanCacheResponse) ProtoMessage() {}

func (x *NotifyScanCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyScanCacheResponse.ProtoReflect.Descriptor instead.
func (*NotifyScanCacheResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\",\n" +
	"\x1aNotifyProcessAssetResquest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x1aNotifyProcessAssetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x06status\x18\x02 \x01(\x0e2\f.AssetStatusR\x06status\"\x18\n" +
	"\x16NotifyScanCacheRequest\"\x19\n" +
	"\x17NotifyScanCacheResponse*9\n" +
	"\vAssetStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\r\n" +
	"\tPROCESSED\x10\x022\xa5\x01\n" +
	"\rWorkerService\x12N\n" +
	"\x12NotifyProcessAsset\x12\x1b.NotifyProcessAssetResquest\x1a\x1b.NotifyProcessAssetResponse\x12D\n" +
	"\x0fNotifyScanCache\x12\x17.NotifyScanCacheRequest\x1a\x18.NotifyScanCacheResponseB\rZ\v/service/pbb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_worker_proto_goTypes = []any{
	(AssetStatus)(0),                   // 0: AssetStatus
	(*NotifyProcessAssetResquest)(nil), // 1: NotifyProcessAssetResquest
	(*NotifyProcessAssetResponse)(nil), // 2: NotifyProcessAssetResponse
	(*NotifyScanCacheRequest)(nil),     // 3: NotifyScanCacheRequest
	(*NotifyScanCacheResponse)(nil),    // 4: NotifyScanCacheResponse
}
var file_worker_proto_depIdxs = []int32{
	0, // 0: NotifyProcessAssetResponse.status:type_name -> AssetStatus
	1, // 1: WorkerService.NotifyProcessAsset:input_type -> NotifyProcessAssetResquest
	3, // 2: WorkerService.NotifyScanCache:input_type -> NotifyScanCacheRequest
	2, // 3: WorkerService.NotifyProcessAsset:output_type -> NotifyProcessAssetResponse
	4, // 4: WorkerService.NotifyScanCache:output_type -> NotifyScanCacheResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		EnumInfos:         file_worker_proto_enumTypes,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
