# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'clip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nclip.proto\"\"\n\x11\x45ncodeTextRequest\x12\r\n\x05input\x18\x01 \x01(\t\"#\n\x12\x45ncodeImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"#\n\x0e\x45ncodeResponse\x12\x11\n\tembedding\x18\x01 \x01(\x0c\"\x13\n\x11GetImageSpecInput\"3\n\x12GetImageSpecOutput\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\xb2\x01\n\x0f\x45ncodingService\x12\x31\n\nEncodeText\x12\x12.EncodeTextRequest\x1a\x0f.EncodeResponse\x12\x33\n\x0b\x45ncodeImage\x12\x13.EncodeImageRequest\x1a\x0f.EncodeResponse\x12\x37\n\x0cGetImageSpec\x12\x12.GetImageSpecInput\x1a\x13.GetImageSpecOutputB\rZ\x0b/service/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013/service/pb'
  _globals['_ENCODETEXTREQUEST']._serialized_start=14
  _globals['_ENCODETEXTREQUEST']._serialized_end=48
  _globals['_ENCODEIMAGEREQUEST']._serialized_start=50
  _globals['_ENCODEIMAGEREQUEST']._serialized_end=85
  _globals['_ENCODERESPONSE']._serialized_start=87
  _globals['_ENCODERESPONSE']._serialized_end=122
  _globals['_GETIMAGESPECINPUT']._serialized_start=124
  _globals['_GETIMAGESPECINPUT']._serialized_end=143
  _globals['_GETIMAGESPECOUTPUT']._serialized_start=145
  _globals['_GETIMAGESPECOUTPUT']._serialized_end=196
  _globals['_ENCODINGSERVICE']._serialized_start=199
  _globals['_ENCODINGSERVICE']._serialized_end=377
# @@protoc_insertion_point(module_scope)
