# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import clip_pb2 as clip__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clip_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EncodingServiceStub(object):
    """Worker service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncodeText = channel.unary_unary(
                '/EncodingService/EncodeText',
                request_serializer=clip__pb2.EncodeTextRequest.SerializeToString,
                response_deserializer=clip__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.EncodeImage = channel.unary_unary(
                '/EncodingService/EncodeImage',
                request_serializer=clip__pb2.EncodeImageRequest.SerializeToString,
                response_deserializer=clip__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.GetImageSpec = channel.unary_unary(
                '/EncodingService/GetImageSpec',
                request_serializer=clip__pb2.GetImageSpecInput.SerializeToString,
                response_deserializer=clip__pb2.GetImageSpecOutput.FromString,
                _registered_method=True)


class EncodingServiceServicer(object):
    """Worker service definition.
    """

    def EncodeText(self, request, context):
        """EncodeText perform text embedding
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeImage(self, request, context):
        """Notify worker to queue unprocessed asset to processing queue.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImageSpec(self, request, context):
        """Return the image spec to be encoded.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncodingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EncodeText': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeText,
                    request_deserializer=clip__pb2.EncodeTextRequest.FromString,
                    response_serializer=clip__pb2.EncodeResponse.SerializeToString,
            ),
            'EncodeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeImage,
                    request_deserializer=clip__pb2.EncodeImageRequest.FromString,
                    response_serializer=clip__pb2.EncodeResponse.SerializeToString,
            ),
            'GetImageSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImageSpec,
                    request_deserializer=clip__pb2.GetImageSpecInput.FromString,
                    response_serializer=clip__pb2.GetImageSpecOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EncodingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EncodingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EncodingService(object):
    """Worker service definition.
    """

    @staticmethod
    def EncodeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EncodingService/EncodeText',
            clip__pb2.EncodeTextRequest.SerializeToString,
            clip__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EncodingService/EncodeImage',
            clip__pb2.EncodeImageRequest.SerializeToString,
            clip__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImageSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EncodingService/GetImageSpec',
            clip__pb2.GetImageSpecInput.SerializeToString,
            clip__pb2.GetImageSpecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
