// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: worker.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "";

/** Status of the asset. */
export enum AssetStatus {
  PENDING = 0,
  PROCESSING = 1,
  PROCESSED = 2,
  UNRECOGNIZED = -1,
}

export function assetStatusFromJSON(object: any): AssetStatus {
  switch (object) {
    case 0:
    case "PENDING":
      return AssetStatus.PENDING;
    case 1:
    case "PROCESSING":
      return AssetStatus.PROCESSING;
    case 2:
    case "PROCESSED":
      return AssetStatus.PROCESSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AssetStatus.UNRECOGNIZED;
  }
}

export function assetStatusToJSON(object: AssetStatus): string {
  switch (object) {
    case AssetStatus.PENDING:
      return "PENDING";
    case AssetStatus.PROCESSING:
      return "PROCESSING";
    case AssetStatus.PROCESSED:
      return "PROCESSED";
    case AssetStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** NotifyProcessAssetRequest */
export interface NotifyProcessAssetResquest {
  id: string;
}

/** NotifyProcessAssetResponse */
export interface NotifyProcessAssetResponse {
  id: string;
  status: AssetStatus;
}

/** NotifyScanCacheRequest */
export interface NotifyScanCacheRequest {
}

/** NotifyScanCacheResponse */
export interface NotifyScanCacheResponse {
}

function createBaseNotifyProcessAssetResquest(): NotifyProcessAssetResquest {
  return { id: "" };
}

export const NotifyProcessAssetResquest: MessageFns<NotifyProcessAssetResquest> = {
  encode(message: NotifyProcessAssetResquest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NotifyProcessAssetResquest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotifyProcessAssetResquest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NotifyProcessAssetResquest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: NotifyProcessAssetResquest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<NotifyProcessAssetResquest>): NotifyProcessAssetResquest {
    return NotifyProcessAssetResquest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NotifyProcessAssetResquest>): NotifyProcessAssetResquest {
    const message = createBaseNotifyProcessAssetResquest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseNotifyProcessAssetResponse(): NotifyProcessAssetResponse {
  return { id: "", status: 0 };
}

export const NotifyProcessAssetResponse: MessageFns<NotifyProcessAssetResponse> = {
  encode(message: NotifyProcessAssetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NotifyProcessAssetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotifyProcessAssetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NotifyProcessAssetResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      status: isSet(object.status) ? assetStatusFromJSON(object.status) : 0,
    };
  },

  toJSON(message: NotifyProcessAssetResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.status !== 0) {
      obj.status = assetStatusToJSON(message.status);
    }
    return obj;
  },

  create(base?: DeepPartial<NotifyProcessAssetResponse>): NotifyProcessAssetResponse {
    return NotifyProcessAssetResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NotifyProcessAssetResponse>): NotifyProcessAssetResponse {
    const message = createBaseNotifyProcessAssetResponse();
    message.id = object.id ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseNotifyScanCacheRequest(): NotifyScanCacheRequest {
  return {};
}

export const NotifyScanCacheRequest: MessageFns<NotifyScanCacheRequest> = {
  encode(_: NotifyScanCacheRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NotifyScanCacheRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotifyScanCacheRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): NotifyScanCacheRequest {
    return {};
  },

  toJSON(_: NotifyScanCacheRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<NotifyScanCacheRequest>): NotifyScanCacheRequest {
    return NotifyScanCacheRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<NotifyScanCacheRequest>): NotifyScanCacheRequest {
    const message = createBaseNotifyScanCacheRequest();
    return message;
  },
};

function createBaseNotifyScanCacheResponse(): NotifyScanCacheResponse {
  return {};
}

export const NotifyScanCacheResponse: MessageFns<NotifyScanCacheResponse> = {
  encode(_: NotifyScanCacheResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NotifyScanCacheResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotifyScanCacheResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): NotifyScanCacheResponse {
    return {};
  },

  toJSON(_: NotifyScanCacheResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<NotifyScanCacheResponse>): NotifyScanCacheResponse {
    return NotifyScanCacheResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<NotifyScanCacheResponse>): NotifyScanCacheResponse {
    const message = createBaseNotifyScanCacheResponse();
    return message;
  },
};

/** Worker service definition. */
export type WorkerServiceDefinition = typeof WorkerServiceDefinition;
export const WorkerServiceDefinition = {
  name: "WorkerService",
  fullName: "WorkerService",
  methods: {
    /** Notify worker to process specific asset. */
    notifyProcessAsset: {
      name: "NotifyProcessAsset",
      requestType: NotifyProcessAssetResquest as typeof NotifyProcessAssetResquest,
      requestStream: false,
      responseType: NotifyProcessAssetResponse as typeof NotifyProcessAssetResponse,
      responseStream: false,
      options: {},
    },
    /** Notify worker to queue unprocessed asset to processing queue. */
    notifyScanCache: {
      name: "NotifyScanCache",
      requestType: NotifyScanCacheRequest as typeof NotifyScanCacheRequest,
      requestStream: false,
      responseType: NotifyScanCacheResponse as typeof NotifyScanCacheResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface WorkerServiceImplementation<CallContextExt = {}> {
  /** Notify worker to process specific asset. */
  notifyProcessAsset(
    request: NotifyProcessAssetResquest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<NotifyProcessAssetResponse>>;
  /** Notify worker to queue unprocessed asset to processing queue. */
  notifyScanCache(
    request: NotifyScanCacheRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<NotifyScanCacheResponse>>;
}

export interface WorkerServiceClient<CallOptionsExt = {}> {
  /** Notify worker to process specific asset. */
  notifyProcessAsset(
    request: DeepPartial<NotifyProcessAssetResquest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<NotifyProcessAssetResponse>;
  /** Notify worker to queue unprocessed asset to processing queue. */
  notifyScanCache(
    request: DeepPartial<NotifyScanCacheRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<NotifyScanCacheResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
