services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: pgvector/pgvector:pg18
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  # Garage S3 Service
  garage:
    image: dxflrs/garage:v2.3.0
    environment:
      GARAGE_DEFAULT_ACCESS_KEY: "GK1234567890ABCDEFGH"
      GARAGE_DEFAULT_SECRET_KEY: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
      GARAGE_DEFAULT_BUCKET: "my-test-bucket"
    volumes:
      - ../garage/garage.toml:/etc/garage.toml
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data
    ports:
      - "3900:3900" # S3 API
      - "3901:3901" # RPC
      - "3902:3902" # Web
    command:
      - /garage
      - server
      - --single-node
      - --default-bucket

  imgproxy:
    image: darthsim/imgproxy:v3
    ports:
      - "8080:8080"
    environment:
      IMGPROXY_KEY: 998815c0f9c53188a267729f1c9642874e4ce943996a5a733daf9ae23a1a7579
      IMGPROXY_SALT: db05ab55dbb501be4915bfde6105ed42f51564bc48d5ad7b27ed674b214f158f
      IMGPROXY_USE_S3: true
      IMGPROXY_S3_REGION: 'garage'
      IMGPROXY_S3_ENDPOINT: http://garage:3900
      IMGPROXY_S3_ENDPOINT_USE_PATH_STYLE: true
volumes:
  postgres-data:
  garage-meta:
  garage-data:


