// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAlbum = `-- name: GetAlbum :one
SELECT id, name, created_at, modified_at, deleted_at, cover FROM albums WHERE id = $1 and deleted_at IS NULL
`

func (q *Queries) GetAlbum(ctx context.Context, id pgtype.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Cover,
	)
	return i, err
}

const getAlbumsWithoutCover = `-- name: GetAlbumsWithoutCover :many
SELECT id, name, created_at, modified_at, deleted_at, cover FROM albums WHERE cover = '' and deleted_at IS NULL
`

func (q *Queries) GetAlbumsWithoutCover(ctx context.Context) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAlbumsWithoutCover)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.Cover,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAlbum = `-- name: GetAllAlbum :many
SELECT id, name, created_at, modified_at, deleted_at, cover FROM albums WHERE deleted_at IS NULL
`

func (q *Queries) GetAllAlbum(ctx context.Context) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAllAlbum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.Cover,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlbumDeleted = `-- name: MarkAlbumDeleted :exec
UPDATE albums
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) MarkAlbumDeleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAlbumDeleted, id)
	return err
}
