// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO
    assets (
        album_id,
        filename,
        type,
        original
    )
VALUES ($1, $2, $3, $4)
RETURNING
    id, album_id, filename, created_at, modified_at, deleted_at, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration, image_embedding
`

type CreateAssetParams struct {
	AlbumID  pgtype.UUID
	Filename string
	Type     AssetTypeT
	Original string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.AlbumID,
		arg.Filename,
		arg.Type,
		arg.Original,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Type,
		&i.Original,
		&i.Preview,
		&i.Thumbnail,
		&i.View,
		&i.ProcessStatus,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ViewWidth,
		&i.ViewHeight,
		&i.ImageFrames,
		&i.VideoDuration,
		&i.ImageEmbedding,
	)
	return i, err
}

const getAlbum = `-- name: GetAlbum :one
SELECT id, name, created_at, modified_at, deleted_at, cover FROM albums WHERE id = $1 and deleted_at IS NULL
`

func (q *Queries) GetAlbum(ctx context.Context, id pgtype.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Cover,
	)
	return i, err
}

const getAlbumAssets = `-- name: GetAlbumAssets :many
SELECT id
FROM assets
WHERE
    album_id = $1
    and deleted_at IS NULL
`

func (q *Queries) GetAlbumAssets(ctx context.Context, albumID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getAlbumAssets, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumsWithoutCover = `-- name: GetAlbumsWithoutCover :many
SELECT id, name, created_at, modified_at, deleted_at, cover FROM albums WHERE cover = '' and deleted_at IS NULL
`

func (q *Queries) GetAlbumsWithoutCover(ctx context.Context) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAlbumsWithoutCover)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.Cover,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAsset = `-- name: GetAsset :one
SELECT id, album_id, filename, created_at, modified_at, deleted_at, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration, image_embedding FROM assets WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Type,
		&i.Original,
		&i.Preview,
		&i.Thumbnail,
		&i.View,
		&i.ProcessStatus,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ViewWidth,
		&i.ViewHeight,
		&i.ImageFrames,
		&i.VideoDuration,
		&i.ImageEmbedding,
	)
	return i, err
}

const getAssetProcessStatus = `-- name: GetAssetProcessStatus :one
SELECT process_status
FROM assets
WHERE
    id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetAssetProcessStatus(ctx context.Context, id pgtype.UUID) (ProcessStatusT, error) {
	row := q.db.QueryRow(ctx, getAssetProcessStatus, id)
	var process_status ProcessStatusT
	err := row.Scan(&process_status)
	return process_status, err
}

const getImageAssetsWithoutEmbedding = `-- name: GetImageAssetsWithoutEmbedding :many
SELECT id, album_id, filename, created_at, modified_at, deleted_at, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration, image_embedding
FROM assets
WHERE
    type = 'image'
    AND deleted_at IS NULL
    AND image_embedding IS NULL
`

func (q *Queries) GetImageAssetsWithoutEmbedding(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, getImageAssetsWithoutEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Filename,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.Type,
			&i.Original,
			&i.Preview,
			&i.Thumbnail,
			&i.View,
			&i.ProcessStatus,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ViewWidth,
			&i.ViewHeight,
			&i.ImageFrames,
			&i.VideoDuration,
			&i.ImageEmbedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingAssets = `-- name: GetPendingAssets :many
SELECT id, album_id, filename, created_at, modified_at, deleted_at, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration, image_embedding
FROM assets
WHERE
    process_status = 'pending'
    AND deleted_at IS NULL
`

func (q *Queries) GetPendingAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, getPendingAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Filename,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.Type,
			&i.Original,
			&i.Preview,
			&i.Thumbnail,
			&i.View,
			&i.ProcessStatus,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ViewWidth,
			&i.ViewHeight,
			&i.ImageFrames,
			&i.VideoDuration,
			&i.ImageEmbedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomAlbumAsset = `-- name: GetRandomAlbumAsset :one
SELECT id, album_id, filename, created_at, modified_at, deleted_at, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration, image_embedding
from assets
WHERE
    type <> 'audio'
    AND album_id = $1
    AND process_status = 'processed'
    AND deleted_at IS NULL
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomAlbumAsset(ctx context.Context, albumID pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getRandomAlbumAsset, albumID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Type,
		&i.Original,
		&i.Preview,
		&i.Thumbnail,
		&i.View,
		&i.ProcessStatus,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ViewWidth,
		&i.ViewHeight,
		&i.ImageFrames,
		&i.VideoDuration,
		&i.ImageEmbedding,
	)
	return i, err
}

const updateAlbumThumbnail = `-- name: UpdateAlbumThumbnail :one
UPDATE albums
SET
    cover = $1,
    modified_at = NOW()
WHERE
    id = $2
    AND deleted_at IS NULL
RETURNING
    id, name, created_at, modified_at, deleted_at, cover
`

type UpdateAlbumThumbnailParams struct {
	Cover string
	ID    pgtype.UUID
}

func (q *Queries) UpdateAlbumThumbnail(ctx context.Context, arg UpdateAlbumThumbnailParams) (Album, error) {
	row := q.db.QueryRow(ctx, updateAlbumThumbnail, arg.Cover, arg.ID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Cover,
	)
	return i, err
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET
    filename = $2,
    type = $3,
    original = $4,
    preview = $5,
    thumbnail = $6,
    view = $7,
    process_status = $8,
    modified_at = NOW(),
    thumbnail_width = $9,
    thumbnail_height = $10,
    view_width = $11,
    view_height = $12,
    image_frames = $13,
    video_duration = $14,
    image_embedding = $15
WHERE
    id = $1
    AND deleted_at IS NULL
RETURNING
    id, album_id, filename, created_at, modified_at, deleted_at, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration, image_embedding
`

type UpdateAssetParams struct {
	ID              pgtype.UUID
	Filename        string
	Type            AssetTypeT
	Original        string
	Preview         string
	Thumbnail       string
	View            string
	ProcessStatus   ProcessStatusT
	ThumbnailWidth  int32
	ThumbnailHeight int32
	ViewWidth       int32
	ViewHeight      int32
	ImageFrames     int32
	VideoDuration   pgtype.Interval
	ImageEmbedding  *pgvector.Vector
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.Filename,
		arg.Type,
		arg.Original,
		arg.Preview,
		arg.Thumbnail,
		arg.View,
		arg.ProcessStatus,
		arg.ThumbnailWidth,
		arg.ThumbnailHeight,
		arg.ViewWidth,
		arg.ViewHeight,
		arg.ImageFrames,
		arg.VideoDuration,
		arg.ImageEmbedding,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Type,
		&i.Original,
		&i.Preview,
		&i.Thumbnail,
		&i.View,
		&i.ProcessStatus,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ViewWidth,
		&i.ViewHeight,
		&i.ImageFrames,
		&i.VideoDuration,
		&i.ImageEmbedding,
	)
	return i, err
}

const updateAssetProcessStatus = `-- name: UpdateAssetProcessStatus :one
UPDATE assets
SET
    process_status = $2,
    modified_at = NOW()
WHERE
    id = $1
    AND deleted_at IS NULL
RETURNING
    id, album_id, filename, created_at, modified_at, deleted_at, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration, image_embedding
`

type UpdateAssetProcessStatusParams struct {
	ID            pgtype.UUID
	ProcessStatus ProcessStatusT
}

func (q *Queries) UpdateAssetProcessStatus(ctx context.Context, arg UpdateAssetProcessStatusParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetProcessStatus, arg.ID, arg.ProcessStatus)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Type,
		&i.Original,
		&i.Preview,
		&i.Thumbnail,
		&i.View,
		&i.ProcessStatus,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ViewWidth,
		&i.ViewHeight,
		&i.ImageFrames,
		&i.VideoDuration,
		&i.ImageEmbedding,
	)
	return i, err
}
