// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
  album_id,
  filename,
  checksum,
  type,
  original,
  size
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, album_id, filename, checksum, created_at, modified_at, deleted_at, size, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration
`

type CreateAssetParams struct {
	AlbumID  pgtype.UUID
	Filename string
	Checksum string
	Type     AssetTypeT
	Original string
	Size     int64
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.AlbumID,
		arg.Filename,
		arg.Checksum,
		arg.Type,
		arg.Original,
		arg.Size,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.Checksum,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Size,
		&i.Type,
		&i.Original,
		&i.Preview,
		&i.Thumbnail,
		&i.View,
		&i.ProcessStatus,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ViewWidth,
		&i.ViewHeight,
		&i.ImageFrames,
		&i.VideoDuration,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, album_id, filename, checksum, created_at, modified_at, deleted_at, size, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration FROM assets WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.Checksum,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Size,
		&i.Type,
		&i.Original,
		&i.Preview,
		&i.Thumbnail,
		&i.View,
		&i.ProcessStatus,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ViewWidth,
		&i.ViewHeight,
		&i.ImageFrames,
		&i.VideoDuration,
	)
	return i, err
}

const getAssetProcessStatus = `-- name: GetAssetProcessStatus :one
SELECT process_status
  FROM assets
  WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAssetProcessStatus(ctx context.Context, id pgtype.UUID) (ProcessStatusT, error) {
	row := q.db.QueryRow(ctx, getAssetProcessStatus, id)
	var process_status ProcessStatusT
	err := row.Scan(&process_status)
	return process_status, err
}

const getPendingAssets = `-- name: GetPendingAssets :many
SELECT id, album_id, filename, checksum, created_at, modified_at, deleted_at, size, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration 
    FROM assets 
    WHERE process_status = 'pending' AND deleted_at IS NULL
`

func (q *Queries) GetPendingAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, getPendingAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Filename,
			&i.Checksum,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.Size,
			&i.Type,
			&i.Original,
			&i.Preview,
			&i.Thumbnail,
			&i.View,
			&i.ProcessStatus,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ViewWidth,
			&i.ViewHeight,
			&i.ImageFrames,
			&i.VideoDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets SET
  filename = $2,
  checksum = $3,
  type = $4,
  original = $5,
  preview = $6,
  thumbnail = $7,
  view = $8,
  process_status = $9,
  modified_at = NOW (),
  thumbnail_width = $10,
  thumbnail_height = $11,
  view_width = $12,
  view_height = $13,
  image_frames = $14,
  video_duration = $15
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, album_id, filename, checksum, created_at, modified_at, deleted_at, size, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration
`

type UpdateAssetParams struct {
	ID              pgtype.UUID
	Filename        string
	Checksum        string
	Type            AssetTypeT
	Original        string
	Preview         string
	Thumbnail       string
	View            string
	ProcessStatus   ProcessStatusT
	ThumbnailWidth  int32
	ThumbnailHeight int32
	ViewWidth       int32
	ViewHeight      int32
	ImageFrames     int32
	VideoDuration   pgtype.Interval
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.Filename,
		arg.Checksum,
		arg.Type,
		arg.Original,
		arg.Preview,
		arg.Thumbnail,
		arg.View,
		arg.ProcessStatus,
		arg.ThumbnailWidth,
		arg.ThumbnailHeight,
		arg.ViewWidth,
		arg.ViewHeight,
		arg.ImageFrames,
		arg.VideoDuration,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.Checksum,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Size,
		&i.Type,
		&i.Original,
		&i.Preview,
		&i.Thumbnail,
		&i.View,
		&i.ProcessStatus,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ViewWidth,
		&i.ViewHeight,
		&i.ImageFrames,
		&i.VideoDuration,
	)
	return i, err
}

const updateAssetProcessStatus = `-- name: UpdateAssetProcessStatus :one
UPDATE assets SET
  process_status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, album_id, filename, checksum, created_at, modified_at, deleted_at, size, type, original, preview, thumbnail, view, process_status, thumbnail_width, thumbnail_height, view_width, view_height, image_frames, video_duration
`

type UpdateAssetProcessStatusParams struct {
	ID            pgtype.UUID
	ProcessStatus ProcessStatusT
}

func (q *Queries) UpdateAssetProcessStatus(ctx context.Context, arg UpdateAssetProcessStatusParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetProcessStatus, arg.ID, arg.ProcessStatus)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.Checksum,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Size,
		&i.Type,
		&i.Original,
		&i.Preview,
		&i.Thumbnail,
		&i.View,
		&i.ProcessStatus,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ViewWidth,
		&i.ViewHeight,
		&i.ImageFrames,
		&i.VideoDuration,
	)
	return i, err
}
