// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const markAssetsDeleted = `-- name: MarkAssetsDeleted :batchexec
UPDATE assets
SET deleted_at = now()
WHERE id = $1
`

type MarkAssetsDeletedBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) MarkAssetsDeleted(ctx context.Context, id []pgtype.UUID) *MarkAssetsDeletedBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(markAssetsDeleted, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &MarkAssetsDeletedBatchResults{br, len(id), false}
}

func (b *MarkAssetsDeletedBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *MarkAssetsDeletedBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
