// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetTypeT string

const (
	AssetTypeTImage    AssetTypeT = "image"
	AssetTypeTAnimated AssetTypeT = "animated"
	AssetTypeTVideo    AssetTypeT = "video"
	AssetTypeTAudio    AssetTypeT = "audio"
)

func (e *AssetTypeT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetTypeT(s)
	case string:
		*e = AssetTypeT(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetTypeT: %T", src)
	}
	return nil
}

type NullAssetTypeT struct {
	AssetTypeT AssetTypeT
	Valid      bool // Valid is true if AssetTypeT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetTypeT) Scan(value interface{}) error {
	if value == nil {
		ns.AssetTypeT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetTypeT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetTypeT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetTypeT), nil
}

type ProcessStatusT string

const (
	ProcessStatusTPending    ProcessStatusT = "pending"
	ProcessStatusTProcessing ProcessStatusT = "processing"
	ProcessStatusTProcessed  ProcessStatusT = "processed"
)

func (e *ProcessStatusT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessStatusT(s)
	case string:
		*e = ProcessStatusT(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessStatusT: %T", src)
	}
	return nil
}

type NullProcessStatusT struct {
	ProcessStatusT ProcessStatusT
	Valid          bool // Valid is true if ProcessStatusT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessStatusT) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessStatusT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessStatusT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessStatusT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessStatusT), nil
}

type Album struct {
	ID         pgtype.UUID
	Name       string
	CreatedAt  pgtype.Timestamptz
	ModifiedAt pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	Cover      string
}

type Asset struct {
	ID              pgtype.UUID
	AlbumID         pgtype.UUID
	Filename        string
	Checksum        string
	CreatedAt       pgtype.Timestamptz
	ModifiedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	Size            int64
	Type            AssetTypeT
	Original        string
	Preview         string
	Thumbnail       string
	View            string
	ProcessStatus   ProcessStatusT
	ThumbnailWidth  int32
	ThumbnailHeight int32
	ViewWidth       int32
	ViewHeight      int32
	ImageFrames     int32
	VideoDuration   pgtype.Interval
}
