// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: worker.proto

package definition

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_NotifyProcessAsset_FullMethodName = "/WorkerService/NotifyProcessAsset"
	WorkerService_NotifyScanCache_FullMethodName    = "/WorkerService/NotifyScanCache"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Worker service definition.
type WorkerServiceClient interface {
	// Notify worker to process specific asset.
	NotifyProcessAsset(ctx context.Context, in *NotifyProcessAssetResquest, opts ...grpc.CallOption) (*NotifyProcessAssetResponse, error)
	// Notify worker to queue unprocessed asset to processing queue.
	NotifyScanCache(ctx context.Context, in *NotifyScanCacheRequest, opts ...grpc.CallOption) (*NotifyScanCacheResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) NotifyProcessAsset(ctx context.Context, in *NotifyProcessAssetResquest, opts ...grpc.CallOption) (*NotifyProcessAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyProcessAssetResponse)
	err := c.cc.Invoke(ctx, WorkerService_NotifyProcessAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) NotifyScanCache(ctx context.Context, in *NotifyScanCacheRequest, opts ...grpc.CallOption) (*NotifyScanCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyScanCacheResponse)
	err := c.cc.Invoke(ctx, WorkerService_NotifyScanCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// Worker service definition.
type WorkerServiceServer interface {
	// Notify worker to process specific asset.
	NotifyProcessAsset(context.Context, *NotifyProcessAssetResquest) (*NotifyProcessAssetResponse, error)
	// Notify worker to queue unprocessed asset to processing queue.
	NotifyScanCache(context.Context, *NotifyScanCacheRequest) (*NotifyScanCacheResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) NotifyProcessAsset(context.Context, *NotifyProcessAssetResquest) (*NotifyProcessAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyProcessAsset not implemented")
}
func (UnimplementedWorkerServiceServer) NotifyScanCache(context.Context, *NotifyScanCacheRequest) (*NotifyScanCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyScanCache not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_NotifyProcessAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyProcessAssetResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).NotifyProcessAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_NotifyProcessAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).NotifyProcessAsset(ctx, req.(*NotifyProcessAssetResquest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_NotifyScanCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyScanCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).NotifyScanCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_NotifyScanCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).NotifyScanCache(ctx, req.(*NotifyScanCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyProcessAsset",
			Handler:    _WorkerService_NotifyProcessAsset_Handler,
		},
		{
			MethodName: "NotifyScanCache",
			Handler:    _WorkerService_NotifyScanCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
