/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AssetTypeT = "animated" | "audio" | "image" | "video";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type ProcessStatusT = "pending" | "processed" | "processing";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Albums {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  modified_at: Generated<Timestamp>;
  name: string;
}

export interface Assets {
  album_id: string;
  checksum: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  filename: string;
  id: Generated<string>;
  modified_at: Generated<Timestamp>;
  original: Generated<string>;
  preview: Generated<string>;
  process_status: Generated<ProcessStatusT>;
  size: Generated<Int8>;
  thumbnail: Generated<string>;
  type: Generated<AssetTypeT>;
  view: Generated<string>;
}

export interface SchemaMigrations {
  version: string;
}

export interface DB {
  albums: Albums;
  assets: Assets;
  schema_migrations: SchemaMigrations;
}
